### ISSUE TITLE
Release of `v1.2.0` causes: Error: Cannot find module 'browserslist-config-baseline'

### ISSUE THREAD

**Issue by u01jmg3** [ChartsCSS/charts.css#145]
Hello,

Thanks for all your efforts with this library.

Since the release of `v1.2.0` (had no issues with `v1.1.0`), when I build my assets with Webpack, I get the following error.

Can you advise?

```
ERROR in ./node_modules/charts.css/dist/charts.min.css (./node_modules/css-loader/dist/cjs.js??clonedRuleSet-11.use[1]!./node_modules/postcss-loader/dist/cjs.js??clonedRuleSet-11.use[2]!./node_modules/charts.css/dist/charts.min.css)
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: Cannot find module 'browserslist-config-baseline'
Require stack:
- C:\node_modules\browserslist\node.js
- C:\node_modules\browserslist\index.js
- C:\node_modules\autoprefixer\lib\autoprefixer.js
- C:\webpack.mix.js
- C:\node_modules\laravel-mix\setup\webpack.config.js
- C:\node_modules\webpack-cli\lib\webpack-cli.js
- C:\node_modules\webpack-cli\lib\bootstrap.js
- C:\node_modules\webpack-cli\bin\cli.js
- C:\node_modules\webpack\bin\webpack.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1212:15)
    at Function.resolve (node:internal/modules/helpers:193:19)
    at Object.loadQueries (C:\node_modules\browserslist\node.js:231:35)
    at Function.select (C:\node_modules\browserslist\index.js:1174:26)
    at C:\node_modules\browserslist\index.js:332:29
    at Array.reduce (<anonymous>)
    at resolve (C:\node_modules\browserslist\index.js:322:32)
    at browserslist (C:\node_modules\browserslist\index.js:431:21)
    at Browsers.parse (C:\node_modules\autoprefixer\lib\browsers.js:61:12)
    at new Browsers (C:\node_modules\autoprefixer\lib\browsers.js:11:26)
    at loadPrefixes (C:\node_modules\autoprefixer\lib\autoprefixer.js:106:20)
    at Object.prepare (C:\node_modules\autoprefixer\lib\autoprefixer.js:129:22)
    at C:\node_modules\postcss\lib\lazy-result.js:181:39
    at Array.map (<anonymous>)
    at new LazyResult (C:\node_modules\postcss\lib\lazy-result.js:179:43)
    at Processor.process (C:\node_modules\postcss\lib\processor.js:53:14)
    at Object.loader (C:\node_modules\postcss-loader\dist\index.js:97:30)

webpack compiled with 1 error
```

**Comment by ramiy** [comment]
@u01jmg3 

The original commit related to your issue: https://github.com/ChartsCSS/charts.css/commit/f371708d47e15cc5fe67692072215cbf36e8eba8

Your error says: `Error: Cannot find module 'browserslist-config-baseline'`

It should be fixed with `npm i`, please update if it works (or not).

**Comment by u01jmg3** [comment]
Nope, `npm i` was the first thing I tried and the issue persists.

The only way I can get things to work is by installing `browserslist-config-baseline` myself which is not ideal.

`npm install browserslist-config-baseline --save-dev`

**Comment by ramiy** [comment]
@u01jmg3 

I'm glad to hear that you found a solution. I'm closing the issue as this is not a problem with Charts.css.

**Comment by u01jmg3** [comment]
> _I'm closing the issue as this is not a problem with Charts.css._

- Hmm I'm not sure we've landed on a great solution - although I've found _a solution_, it's not ideal and isn't, for example, mentioned in your setup instructions. Should it be?

- Also, `v1.1.0` played nicely with Webpack, but `v1.2.0` has this issue. If it's not a problem with `charts.css` and this change f371708, where does the issue lie?

- Has `v1.2.0` been tested with a blank Webpack project and confirmed as working? I only ask because I don't see any test coverage to ensure `charts.css` works with the likes of Webpack, Vite, etc.

**Comment by filmaj** [comment]
Consumers of charts.css can bundle how they wish, but should this project guarantee compatibility with all bundlers? That doesn't seem reasonable to me.

I am not familiar with webpack, but `browserslist-config-baseline` is used in charts.css for testing, which is why it is listed as a `devDependency` in this project's `package.json` - it's not required for consumption. It's unclear to me why webpack needs a reference to it, but that seems like webpack's problem and not charts.css'.

**Comment by u01jmg3** [comment]
- Sure - but what was working is now "broken". (Or at least an undocumented extra step is now required.) Most of the time, this would be seen as a breaking change, and in that case, from experience, other packages would have bumped to `v2.0.0` to be on the safe side.
- If support isn't guaranteed for Webpack, then documenting this somewhere could be a compromise (happy to raise a PR given the nod).
- To me, this feels like the issue has been swiftly brushed under the carpet, but then again, so far, I am the only person who has raised this.

**Comment by ramiy** [comment]
@u01jmg3 I understand your point. Maybe there should be documentation. But it will be in a separate Repo - https://github.com/ChartsCSS/ChartsCSS.org

**Comment by stacy-rendall** [comment]
> Consumers of charts.css can bundle how they wish, but should this project guarantee compatibility with all bundlers? That doesn't seem reasonable to me.
> 
> I am not familiar with webpack, but `browserslist-config-baseline` is used in charts.css for testing, which is why it is listed as a `devDependency` in this project's `package.json` - it's not required for consumption. It's unclear to me why webpack needs a reference to it, but that seems like webpack's problem and not charts.css'.

Although `browserslist-config-baseline` has been listed as a `devDependency` that doesn't necessarily mean it won't be required by users of this package - here is a recent write-up that I found insightful on this topic: https://angelika.me/2024/11/11/dependencies-vs-dev-dependencies-javascript-apps/

The problem is that in [f371708](https://github.com/ChartsCSS/charts.css/commit/f371708d47e15cc5fe67692072215cbf36e8eba8) `package.json` was modified such that `"browserslist"` now equals only `["extends browserslist-config-baseline"]`. Any user attempting to use this library with any bundler now requires `browserslist-config-baseline` to parse the browserlist...

Potential fixes:

1. revert [f371708](https://github.com/ChartsCSS/charts.css/commit/f371708d47e15cc5fe67692072215cbf36e8eba8) 
2. Move `browserslist-config-baseline` to `dependencies`
3. Add to documentation stating that users also need to install ` browserslist-config-baseline`

**Comment by ramiy** [comment]
@stacy-rendall Thank you for the detailed answer. It clarifies the issue.

I’ve thought about this quite a bit over the past week, and I’ve decided not to revert the change and not to move `browserslist-config-baseline` to `dependencies`.

**Charts.css** is not a JavaScript library, therefore it has no dependencies. All the packages listed under `devDependencies` are used solely during the build step.

That said, I understand that many users integrate **Charts.css** with build tools like **Webpack** and **Vite**. To address this, the documentation on [ChartsCSS.org](https://chartscss.org/) will be updated with clearer guidance for these use cases.

**Comment by stacy-rendall** [comment]
> [@stacy-rendall](https://github.com/stacy-rendall) Thank you for the detailed answer. It clarifies the issue.
> 
> I’ve thought about this quite a bit over the past week, and I’ve decided not to revert the change and not to move `browserslist-config-baseline` to `dependencies`.
> 
> **Charts.css** is not a JavaScript library, therefore it has no dependencies. All the packages listed under `devDependencies` are used solely during the build step.
> 
> That said, I understand that many users integrate **Charts.css** with build tools like **Webpack** and **Vite**. To address this, the documentation on [ChartsCSS.org](https://chartscss.org/) will be updated with clearer guidance for these use cases.

Great, cheers!

**Comment by hyunbinseo** [comment]
Why not remove `package.json`'s `browserlist` key before publishing the package?

I am sure the `prepublishOnly` lifecycle script can be utilized according to the current workflow.

Personal reproduction: https://github.com/hyunbinseo/charts.css-145
